from .abc import AbstractIdentityPolicy, Identity
from typing import Any, Union
import aiohttp.web

class sentinel: ...


class CookiesIdentityPolicy(AbstractIdentityPolicy):
    def __init__(self) -> None: ...
    async def identify(self, request: aiohttp.web.Request) -> Identity: ...
    async def remember(self, request: aiohttp.web.Request, response: aiohttp.web.StreamResponse, identity: Identity, max_age: Union[sentinel, int]=..., **kwargs: Any) -> None: ...
    async def forget(self, request: aiohttp.web.Request, response: aiohttp.web.StreamResponse) -> None: ...
